### ISSUE TITLE
'excludePing' cannot be null

### ISSUE THREAD

**Issue by marwanhammad** [lord-kyron/terraform-provider-phpipam#52] opened 2022-12-19 12:46 UTC
Create new ip address return 500 error 

phpipam_address.newip: Creating...
╷
│ Error: Non-API error (500 Internal Server Error): {"code":500,"success":0,"message":"Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'excludePing' cannot be null","time":0.008}
│
│   with phpipam_address.newip,
│   on ipam.tf line 33, in resource "phpipam_address" "newip":
│   33: resource "phpipam_address" "newip"{
│
╵

**Comment by lord-kyron** [comment] 2022-12-19 15:10
@pavel-z1 can you help with this one?

**Comment by pavel-z1** [comment] 2022-12-21 12:39
Hi @marwanhammad 

Can you please provide some example how I can reproduce this error?

**Comment by lord-kyron** [comment] 2023-02-24 10:19
@marwanhammad - can you please provide some example how we can reproduce this, or I will close this one!
Thanks!

**Comment by lord-kyron** [comment] 2023-03-06 09:04
Closing because of inactivity.

**Closed by lord-kyron** 2023-03-06 09:04 UTC
