### ISSUE TITLE
Terraform crashes when using custom_field_filter

### ISSUE THREAD

**Issue by basic39** [lord-kyron/terraform-provider-phpipam#19] opened 2020-06-30 13:45 UTC
Hello,

I am trying to use terraform-provider-phpipam to get a free IP from ipam. This IP will be used after to deploy VMs. The best way to identify the subnet is in our case the VLAN-ID. 

For this purpose I need to find out the "phpipam_subnet". This couldn't be done by VLAN directly. The only way I found in the documentation is by custom_field_filter:
```
data "phpipam_subnet" "subnet" {
  section_id = data.phpipam_section.section.id
  custom_field_filter = {
    VLAN = ".*1234.*"
  }
}
```

But this cause a Terraform crash:
[ipam-tf-crash.txt](https://github.com/lord-kyron/terraform-provider-phpipam/files/4852182/ipam-tf-crash.txt)

The same config works, if I use "description_match" instead of "custom_field_filter". 

Can you help me find a possibility to identify the subnet by VLAN?

Versions:
terraform-provider-phpipam: v1.1
Terraform: v0.12.25 and v0.12.28(both crashes)
phpIPAM: v1.4
go: 1.13.11
CentOS 7.8.2003

**Comment by pavel-z1** [comment] 2020-06-30 19:24
Hi @lord-kyron ,
I think that this is the same issue, that described in issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/17

I've tested from my side. Can confirm that terraform crash.
Unfortunately, I don't know much about custom fields structure. Maybe, you shed light on a solution to this problem?

**Comment by lord-kyron** [comment] 2020-06-30 20:46
I am not getting crashes, but cannot make those fileds to work as I expect. For example I add some custom fields on hand to some addresses and try to search them but always getting empty response when use field for multiple addresses. When I use the onebfor single first match address I am getting message that there are multiple objects found... Cannot getvwhat is going on. @pavel-z1 - maybe you can try to refine the code for those fields and maybr add support for searching by vlan id if you have time?

**Comment by pavel-z1** [comment] 2020-07-12 14:35
Duplicate of #17

**Comment by pavel-z1** [comment] 2020-07-12 14:36
Need deep investigating of PHPIPAM responce format.
I will try to check the source code next week.

**Comment by pavel-z1** [comment] 2020-07-12 14:38
Further progress will be provided in this issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/17

**Closed by pavel-z1** 2020-07-12 14:38 UTC
