### ISSUE TITLE
phpipam  failing for https

### ISSUE THREAD

**Issue by thatsk** [lord-kyron/terraform-provider-phpipam#10] opened 2020-05-15 10:47 UTC
Hello ,
i am trying to use this provider for vsphere to manage IP to VM. I go through documentation and configured phpipam 1.4.
below is screenshot.
![image](https://user-images.githubusercontent.com/15324013/82042426-755e6400-96c7-11ea-9bdf-329e58315468.png)
but when I am trying to plan the terraform it is giving me error.

```YAMl
Error: Error logging into PHPIPAM: HTTP protocol error: Post https://phpipam/api/test/user/: x509: certificate signed by unknown authority

  on ipam.tf line 1, in provider "phpipam":
   1: provider "phpipam" {
```

**Comment by thatsk** [comment] 2020-05-15 10:47
is it due to i am using phpipam 1.4 or something else

**Comment by thatsk** [comment] 2020-05-15 10:47
```YAMl

**Comment by thatsk** [comment] 2020-05-15 10:48
let me know if i am doing anything wrong.

**Comment by thatsk** [comment] 2020-05-15 11:30
i am using openssl certs with following documentation 
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-apache-for-centos-7

**Comment by thatsk** [comment] 2020-05-15 12:01
if i try to use http it is giving me following error.
Error: Error logging into PHPIPAM: Error from API (503): Invalid enc_request

**Comment by pavel-z1** [comment] 2020-05-16 08:43
Duplicate of #9 
@thatsk , please follow the new feature "**insetsure**" in the issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/9

**Closed by pavel-z1** 2020-05-16 08:43 UTC
