### ISSUE TITLE
Using PHPIPAM with the count metaparameter

### ISSUE THREAD

**Issue by blurtonator** [lord-kyron/terraform-provider-phpipam#12] opened 2020-05-15 17:06 UTC
Hello,
Is it possible to use 'count' to register more than one address? When I try, I get the same address for every VM. My example below is two virtual machines, each with an address from PHPIPAM.

```
data "phpipam_subnet" "service_subnet" {
  count          = "${var.service_cidr != "" ? var.node_count : 0}"
  subnet_address = "${split("/", var.service_cidr)[0]}"
  subnet_mask    = "${split("/", var.service_cidr)[1]}"
}

data "phpipam_first_free_address" "service_address" {
  count     = "${var.service_cidr != "" ? var.node_count : 0}"
  subnet_id = data.phpipam_subnet.service_subnet[count.index].subnet_id
}

resource "phpipam_address" "service_address" {
  count         = "${var.service_cidr != "" ? var.node_count : 0}"
  ip_address = data.phpipam_first_free_address.service_address[count.index].ip_address
  subnet_id  = data.phpipam_subnet.service_subnet[0].subnet_id
  hostname = "xxxx"
  lifecycle {
    ignore_changes = [
      subnet_id
    ]
  }
}
```

**Comment by pavel-z1** [comment] 2020-05-16 09:06
Hi @blurtonator ,

phpIPAM 1.4 and loved had bug with locking of new registered IPs.
This bug was fixed here https://github.com/phpipam/phpipam/issues/2960

You need update phpIPAM files to the latest version 1.4 commit.
Also, try to enable transaction locks for you API:
![image](https://user-images.githubusercontent.com/53462452/82115778-895ca100-976d-11ea-91e8-9256cd154ca6.png)


I hope that this will help you to solve issue.

**Comment by pavel-z1** [comment] 2020-05-16 09:23
Duplicate of #7

**Comment by lord-kyron** [comment] 2020-05-16 09:58
Shouldn't this one be closed as well? This is know bug and the fixes for also know and described already.

**Comment by blurtonator** [comment] 2020-05-16 17:42
Perfect. Thank you!

**Closed** 2020-05-16 17:43 UTC
